# /etc/security/limits.d/99-gaming.conf — Arch Gaming OS
# Limiti utente per gaming

@gamemode  -  nofile   1048576
@gamemode  -  rtprio   98
@gamemode  -  memlock  unlimited
@gamemode  -  nice     -20
